### ISSUE TITLE
你好，我是购买了《macOS 文件管理指南》的读者

### ISSUE THREAD

**Issue by Stevenhell32** [BlackwinMin/automator-gallery#2]
请问，您文章中Automator的workflow在哪里下载？我File Comment无法下载，找不到download。后来，我用Safari浏览器右键>下载链接为…，下载出来的workflow无法用Automator打开。谢谢！

**Comment by BlackwinMin** [comment]
Steven君：GitHub 不是这样工作的，请参考这个网页：https://www.wikihow.com/Download-a-File-from-GitHub
另，我已经更新了文件，你应该可以在这里下载了：https://github.com/BlackwinMin/Automator-gallery/tree/master/File%20Comment/File%20Comment.workflow.zip

**Comment by Stevenhell32** [comment]
谢谢大佬！
